export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'

export const LOGOUT_USER = 'LOGOUT_USER'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const LIST_USER_MESSAGE_ERROR_RESET = 'LIST_USER_MESSAGE_ERROR_RESET'

export const CONFIRM_USER_REQUEST = 'CONFIRM_USER_REQUEST'
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS'
export const CONFIRM_USER_FAIL = 'CONFIRM_USER_FAIL'

export const LIST_USER_PROFILE_REQUEST = 'LIST_USER_PROFILE_REQUEST'
export const LIST_USER_PROFILE_SUCCESS = 'LIST_USER_PROFILE_SUCCESS'
export const LIST_USER_PROFILE_FAIL = 'LIST_USER_PROFILE_FAIL'
